# Verwende das offizielle Ubuntu-Basisimage
FROM ubuntu:latest

# Aktualisiere das Paketrepository und installiere Nginx
# RUN apt-get update && apt-get install -y nginx
RUN apt-get update && apt-get install -y \
    nginx \
    openssh-client \
    curl \
    python3.9 \
    python3-pip \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Kopiere eine lokale Konfigurationsdatei in den Container (falls erforderlich)
COPY ./nginx/nginx.conf /etc/nginx/nginx.conf
COPY ./service_management /app

WORKDIR /app

# Installiere die Anwendungsabhängigkeiten
RUN pip install -r requirements.txt

# Definiere, welcher Port von Nginx bereitgestellt wird
EXPOSE 80

# Starte den Nginx-Dienst beim Start des Containers
CMD python3 app.py; ["nginx", "-g", "daemon off;"]
